language: node_js
cache: npm
node_js:
- '8'
matrix:
  include:
  - os: osx
    install:
    - cd native/electron
    - npm i
    - cd ../../scripts
    - npm i
    - cd ..
    script:
    - cd scripts
    - npm run build
    - cd ../native/electron
    - npm run build
    - npm run package:mac
    - cd ../..
  - os: windows
    install:
    - cd native/electron
    - npm i
    - cd ../../scripts
    - npm i
    - cd ..
    script:
    - cd scripts
    - npm run build
    - cd ../native/electron
    - npm run build
    - npm run package:windows
    - cd ../..
deploy:
  provider: releases
  api_key:
    secure: tDeGjhTFBUHA5r0bXCXJ15ODkjeW2EnJYE6RbChP3yZ18FvVxhG/Yam/zENhPpqtFmUL066wKQk6d5oDqjnFJISMd3+nksjrCUD+wqPWrd+aflVqzQhX3hjP9b+IuClUeKGRFiy/Ywe3W90eHjMnBfxqGfs2iheRECZFXPP9Ju5pnG6KgVXjKMZOb/8+DQzclmf0xXe764lF0KjsrKwxKhFjHI2aLnAQzAhnSxIB8skfzSEue6nUKewn0+M2ctc9lzhjCX4ufZgspIhGJ0/LvgvhJLSKoxNCQpqSR9xN+Sa5t7hjTq3u4x2lYMSNlKlVgD/TbZGOltGiUMNnJ4mJfrWl/ZHjPu8XzoKjWlOHKdbJuBZZ5L2ERYDkKEBSz9DdQMh4HPp6HihckvxAU62igxYseejA+kVxz2/fWeITyO2RY9EC4rVKb9kLcSuJ4o1PFmM/XIRia5B8SbAGeWV1lJJk/AmkRabRzuxI/5w0gpFttx+kj2SfuMjYOqzOEzVKYqYa1TqgeXYEA2evrngIxAEHnCQ7liQT+XLkeV6LAz7fqr/oALe41pnYir1kKyvrnSE8MahGNORtFmcnq3EzuKHMTGO7z/6QtMi47bI7P5altsarnUlMXFyMVZBsbhHZV8WEiI0/LPBDP4mfcKdJ+i2TpUxWArzy4iz4E/kSm3E=
  file_glob: true
  skip_cleanup: true
  file: native/electron/packaged/*
